apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-service-cloudrun-main
spec:
  template:
    spec:
      containers:
        - image: gcr.io/cascade-454406/springboot-service
          env:
            - name: ENV
              value: main
            - name: URL
              value: https://main
            - name: PASSWORD
              value: secretmain
            - name: FEATURE_FLAG_X
              value: true
            - name: SUPPORT_EMAIL
              value: main-support@yourdomain.com
          envFrom:
            - configMapRef:
                name: springboot-config-main
      containerConcurrency: 80
  traffic:
    - latestRevision: true
      percent: 100
