apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-service-cloudrun-dev
spec:
  template:
    spec:
      containers:
        - image: gcr.io/cascade-454406/springboot-service
          env:
            - name: ENV
              value: dev
          envFrom:
            - configMapRef:
                name: springboot-config-dev
      containerConcurrency: 80
  traffic:
    - latestRevision: true
      percent: 100
