apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-service-cloudrun-dev
spec:
  template:
    spec:
      containers:
        - image: gcr.io/cascade-454406/springboot-service
          env:
            - name: ENV
              value: dev
            - name: URL
              value: https://dev
            - name: PASSWORD
              value: secretdev
            - name: FEATURE_FLAG_X
              value: true
            - name: SUPPORT_EMAIL
              value: dev-support@yourdomain.com           

      containerConcurrency: 80
  traffic:
    - latestRevision: true
      percent: 100
